name: psy-dev
services:
  nginx:
    image: ghcr.io/haozi/nginx:1.27.4-alpine
    volumes:
      - ../config/nginx.dev.conf:/etc/nginx/conf.d/default.conf
      - ../keys:/etc/keys
    ports:
      - 9998:80
      - 9999:443
    depends_on:
      - fastapi

  fastapi:
    build:
      context: ../Python/
      dockerfile: Dockerfile
    platform: linux/amd64
    image: ghcr.io/haozi/psy-fastapi:dev-latest
    volumes:
      - ../Python:/app
    command:
      ["fastapi", "dev", "app/main.py", "--host", "0.0.0.0", "--port", "8000"]

  # mysql-local-test-master:
  #   image: ghcr.io/haozi/mysql:9.2.0-oraclelinux9
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: rootpassword
  #     MYSQL_DATABASE: psy-test-db
  #     MYSQL_USER: myuser
  #     MYSQL_PASSWORD: mypassword
  #   ports:
  #     - 63406:3306
  #   volumes:
  #     - psy-dev-data:/var/lib/mysql:cached

  postgres-local-test-master:
    image: ghcr.io/haozi/postgres:17.5-bookworm
    restart: always
    environment:
      POSTGRES_DB: psy-test-db
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - 65432:5432
    volumes:
      - psy-dev-data:/var/lib/postgresql:cached

  # phpmyadmin:
  #   image: ghcr.io/haozi/phpmyadmin:5.2.2-apache
  #   environment:
  #     PMA_HOST: mysql-local-test-master
  #     PMA_PORT: 3306
  #     PMA_USER: root
  #     PMA_PASSWORD: rootpassword

  # deepseek-r1-8b:
  #   build:
  #     context: ../LLM/deepseek-r1:8b/
  #     dockerfile: Dockerfile
  #   platform: linux/amd64
  #   image: ghcr.io/haozi/ollama0.6.2-deepseek-r1-8b:dev-latest
  #   command: ["ollama", "serve"]

  redis:
    image: ghcr.io/haozi/redis:7.4.2-alpine
    # ports:
    #   - 56379:6379

volumes:
  psy-dev-data:
# networks:
#   default:
#     name: psy-dev
